# Generated by Django 6.0.2 on 2026-03-19 22:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
